services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    networks:
      - proxy-tier
    restart: unless-stopped

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
    networks:
      - proxy-tier
    restart: unless-stopped

  portfolio:
    image: bisocm/portfolio:latest
    container_name: portfolio
    environment:
      VIRTUAL_HOST: portfolio.bisocm.org
      LETSENCRYPT_HOST: portfolio.bisocm.org
      LETSENCRYPT_EMAIL: bisocc.m@gmail.com
    networks:
      - proxy-tier
    restart: unless-stopped

networks:
  proxy-tier: { }

volumes:
  nginx_certs: { }
  nginx_vhost: { }
  nginx_html: { }